eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: catalog-service
  rabbitmq:
    sleuth:
      enabled: true
  cloud:
    openfeign:
      clients:
        serie-service:
          url: http://serie-service
          name: serie-service
        movie-service:
          url: http//movie-service
          name: movie-serie
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
      data:
       mongodb:
          database: catalog
          port: 27019
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
rabbitmq:
  password: guest
  username: guest
  port: 5672
  host: localhost

server:
  port: ${PORT:${SERVER_PORT:0}}